{"id": "CVE-2020-28318", "sourceIdentifier": "vulnerabilitylab@mend.io", "published": "2021-01-26T18:15:49.757", "lastModified": "2023-11-07T03:21:17.740", "vulnStatus": "Rejected", "cveTags": [], "descriptions": [{"lang": "en", "value": "Rejected reason: DO NOT USE THIS CANDIDATE NUMBER. ConsultIDs: none. Reason: The CNA or individual who requested this candidate did not associate it with any vulnerability during 2020. Notes: none"}], "metrics": {}, "references": [], "techniques": [], "technical_analysis": "No exploitation details or mitigation information available for this vulnerability. The CVE ID has been rejected and is not to be used.", "executive_analysis": {"Overview": "The vulnerability CVE-2020-28318 has been rejected and is not considered valid. It is recommended to focus on other vulnerabilities and take measures to protect against them.", "Business Impact": "The rejection of the vulnerability does not pose any significant business risk. Cybersecurity teams should continue to focus on other vulnerabilities and take measures to protect against them.", "Technical Impact": "No technical impact is associated with this vulnerability, as it has been rejected.", "Mitigation Strategies": "No mitigation strategies are necessary, as the vulnerability is not considered valid.", "Recommendations": "Cybersecurity teams should prioritize other vulnerabilities and take measures to protect against them.", "Conclusions": "No conclusions can be drawn from this rejected vulnerability."}}